### ISSUE TITLE
Upstream dependencies no longer published?

### ISSUE THREAD

**Issue by 0o-de-lally** [jbarszczewski/tauri-svelte-template#3]
Hey there, thanks for setting this up. Super helpful.

Here's a quick fix to the Cargo.toml.

tauri-build = "^1.0.0-beta-rc.1" no longer exists on crates.io. So I suggest changing it to `1.0.0-beta.1`

Thanks again!

**Comment by jbarszczewski** [comment]
Hi,
thanks for letting me know. It seems that build I've used has been yanked.  I've updated them to the latest version (commit 6a2eb036ef81c42f1292365eec3ad96aa13ad822) , if you can test if all works now that would be great!

**Comment by 0o-de-lally** [comment]
Looks good. Those are the changes I made as well. The Tauri folks advised to do `yarn tauri deps update`.
Thanks again!

**Comment by jbarszczewski** [comment]
Glad that was an easy fix. Thanks again for spotting it!
