### ISSUE TITLE
Error running yarn tauri dev

### ISSUE THREAD

**Issue by daryl-williams** [jbarszczewski/tauri-svelte-template#5]
Hello @jbarszczewski,

I ran across your template while looking for rust/tauri/svelte tutorials and it helps a lot but I am getting the following error:

`[rollup-plugin-svelte] The following packages did not export their `package.json file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.
- @tauri-apps/api`

I did find the following entry for @tauri-apps/api in package.json:

`"@tauri-apps/api": "^1.0.0-beta-rc.3"`

under the devDependencies section but I'm afraid I do not have enough experience to figure this out and I'm hoping you might be able to shed some light on the matter.

Best Regards,

Daryl Williams

**Comment by jbarszczewski** [comment]
Hi @daryl-williams,
Are you on the newest rust version? (I think it's 1.61.0)
Also did you just create an empty project based on the template and that doesn't run?
Tauri has a very active development so it might be a good time for me to update this template with the latest version etc.

Thanks,
Jakub

**Comment by daryl-williams** [comment]
Hi Jacob,

Thank’s for your swift reply. I am using rustc 1.59.0 (9d1b2106e 2022-02-23) and I have tried the tutorial several times, both cloning and using the “Use this template” button. I can’t discount that this is some stupid newbie(me) mistake. 

Daryl Williams
***@***.***

Oops, I just hit send by accident but just wanted to say the error I am seeing is consistent and reproducible but have also seen it in other examples, so it may not be anything in your code.

Thanks again,

Daryl

**Comment by jbarszczewski** [comment]
Thanks for the info. I've managed to reproduce the issue and once I have a solution, I will let you know!

Thanks,
Jakub

**Comment by jbarszczewski** [comment]
Hi Daryl,
I've updated Tauri packages to latest release candidate (14) and now got the app working again. Please checkout the latest version and let me know if it's fixed for you as well.

**Comment by daryl-williams** [comment]
Hi Jakub,

Thanks for the update, I can confirm that it is now working with MacOS 12.4 on an M1 MacBook Air, and thanks again for the template.

D

Daryl Williams
***@***.***

**Comment by jbarszczewski** [comment]
That's great to hear! I hope it will be useful to you.

Thanks,
Jakub
